### ISSUE TITLE
SyntaxError: Unexpected token c in JSON at position 0

### ISSUE THREAD

**Issue by riyas50** [network-international/ngenius-woocommerce-plugin#1]
I'm facing issue with WooCommerce plugin. The above mentioned error throws while trying to place order. Nothing is recorded in log file even though the log is enabled.
![image](https://user-images.githubusercontent.com/18095350/173190613-fcf87064-88b2-4eca-b06f-bc1a40212694.png)

**Comment by riyas50** [comment]
Theme: Woostify
Installed Plugins:
![image](https://user-images.githubusercontent.com/18095350/173190775-70eaa585-7835-43f1-9b98-b440a3f25e95.png)

**Comment by riyas50** [comment]
Plugin Configuration:
![image](https://user-images.githubusercontent.com/18095350/173190885-ea25d78a-8a0f-45c2-b750-aa5c844bd6c5.png)

**Comment by Ihab-Breich** [comment]
@riyas50 Having the same issue. Did you solve the problem?

**Comment by riyas50** [comment]
@Ihab-Breich, No, I could not resolve it myself. This is a sandbox environment, I'm waiting for a response from author. Also send an email for support.

**Comment by Ihab-Breich** [comment]
@riyas50 Could you please keep me updated in case of any update? Thank you in advance

**Comment by riyas50** [comment]
@Ihab-Breich Sure, If I'm able to resolve it through other channels, I'll post the resolution here.

**Comment by Ihab-Breich** [comment]
Hello @riyas50, did you end up solving the problem?

**Comment by riyasalmoe** [comment]
> 

Hello Ihab,
The developer team responded to my email saying that there were no issues when they tested the solution. And pointed me to NI. But no clear answer arrived. The error is very generic about the token. 

So many people I spoke to could not reach the right tech person from NI. When you register @ NI you receive two emails. I with the credentials and activation, the other asking for official documents. I assume the onboarding process must be done to get the testing to function. I'm waiting for the documents to get ready so that I can call them back and re-initiate testing. Once the test is successful, I'll close this issue.

**Comment by Ihab-Breich** [comment]
@riyasalmoe I communicated with the n-genius support team and they provided me with the latest version of n-genius plugin version 2.0.2. Find attached the plugin
[ngenius-v-2.0.2.zip](https://github.com/network-international/ngenius-woocommerce-plugin/files/9000578/ngenius-v-2.0.2.zip)

**Comment by riyasalmoe** [comment]
@Ihab-Breich 
Thank you!!
Are you able to test with this version sucsessfully?

**Comment by Ihab-Breich** [comment]
@riyasalmoe Yes

**Comment by riyasalmoe** [comment]
@Ihab-Breich 
I tested the plug-in, and everything was fine, but finally when it call back, it reported an invalid order ID!!

**Comment by Ihab-Breich** [comment]
@riyasalmoe  This is another error I guess, not related to the previous one. I have no idea honestly, sorry

**Comment by riyas50** [comment]
Version 2.0.2 resolved the issue. The release version must be updated to 2.0.2. As of closing this issue, the release version is 1.0.1
